name: finance_manager_yankovych_ki_401
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/cloud.png
    - assets/images/start.png
    - assets/images/error.png
    - assets/images/sun.png
    - assets/images/snow.jpg
    - assets/images/rain.png
    - assets/images/thunderstorm.png
    - assets/images/fog.png