name: finance_manager_yankovych_ki_401
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  fl_chart: ^0.40.0
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  flashlight_plugin:
    path: flashlight_plugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/pagenavigation/page_profile.png
    - assets/images/pagenavigation/page_transactions.png
    - assets/images/pagenavigation/page_home.png
    - assets/images/page_home_logo.png
    - assets/images/profile-user.png